### ISSUE TITLE
Thoughts on upstreaming?

### ISSUE THREAD

**Issue by WhyNotHugo** [nihaals/clap-complete-command#12]
The types here are very useful, and it feels like `clap_complete` should actually include them.

Do you have any thoughts on pushing the helpers in this crate as additions to the upstream `clap_complete` crate? Has this been discussed before?

**Comment by nihaals** [comment]
This would be nice, but there are a few things that make it hard:

- `clap_complete_fig` is a separate crate that depends on `clap_complete`
  - This adds a circular dependency and the crates would need to be merged
- `clap_complete` uses the same major version as `clap`, but this crate's smoother API would include breaking changes
- `clap_complete` is unlikely to include extra things that just fit in well with the API like #10
- `clap_complete` is unlikely to include third-party/smaller `clap_complete::Generator`s created in the future (and there would again be a circular dependency, unless every generator is added to upstream, which is also unlikely), while this crate can add them as features

For these reasons, I think there will always be a use for a wrapper crate separating the traits and generators from the actual interface for people to use, and implementing this yourself in each project can feel a bit awkward and cause duplication (which is what lead to me making this crate).

It's also important to note that some of these are [intentional design decisions](https://github.com/clap-rs/clap/commit/88a335ff971ff0ca55e224e1599890c5691d8fb8) made by `clap_complete` and so make sense for them.

**Comment by WhyNotHugo** [comment]
Thanks for the detailed answer. It's all very clear, I've nothing to add. :)
